### ISSUE TITLE
Logo Designs [600 PTS Total for 6 LOGOs]

### ISSUE THREAD

**Issue by Qaezel** [Qaezel/invictus-website#1]
You can submit your logos here.

**Comment by infovortice2013** [comment]
hi i like to do logos, is work abailable? i can put in heradric shield a couple of ramping horses at sides to remember  invictus

![1218134319453huella-dedodn](https://f.cloud.github.com/assets/6284117/1820757/0cc50078-7105-11e3-8d49-ed7616b58379.jpg)
![escudoarmas](https://f.cloud.github.com/assets/6284117/1820758/139a14ce-7105-11e3-8c4b-83f1de2988d2.jpg)

**Comment by infovortice2013** [comment]
![111](https://f.cloud.github.com/assets/6284117/1825060/f3646486-71a7-11e3-8a8d-ca1eb5e84075.jpg)
![11](https://f.cloud.github.com/assets/6284117/1825062/f5e67118-71a7-11e3-88a0-dfc729c49ac3.jpg)

**Comment by Qaezel** [comment]
They're looking for something that bankers would respond to. Look at stock and commodity sites for inspiration. Thanks for helping. If you could state that you're working on this on my trello account, that would be great. Just post a comment in the to-do. https://trello.com/b/CfPabY5x/invictus-website

**Comment by infovortice2013** [comment]
![can-ojistock-photo_csp2047794](https://f.cloud.github.com/assets/6284117/1827470/4cbe0522-7235-11e3-9e7b-ed3981f4bfcd.jpg)

**Comment by Qaezel** [comment]
This is really amazing. I showed this to a lot of people and they loved it. You should put it in the bitshares' forum. Remember, there are other teams too.

**Comment by infovortice2013** [comment]
:) ok its done

thanks

**Comment by infovortice2013** [comment]
if they like it i can adapt to bitshares, and finish good, this is a preview

**Comment by bytemaster** [comment]
Honestly, I don't care for any of these logos.  Too dark.

Also the Key metaphor is the wrong idea, we are going more for Quixote related themes.

**Comment by Qaezel** [comment]
Thanks for the feedback.

**Comment by infovortice2013** [comment]
jaja yeah my pics looks dark like pirate bay!,  I see the diference of stye
but if you like the idea of dactilar stamp or other i can change style and
swich to mac icons style, with some blue color background and white lines
more friendly.

you like the idea of quixote and moon to work more on it, or try to create
other composite new ?

all the pics i upload its for take and idea, not are final works sure, so
if like any idea for future but dont like how this looks like im ready to
change it.

for me its luxury colaborate or try it :)

2014/1/1 Jeremy notifications@github.com

**Comment by mjbmonetarymetals** [comment]
Invictus + bitshares logo ideas 

https://www.dropbox.com/s/zt8ftt34c2y7wh4/BITSHARES2.png
https://www.dropbox.com/s/9k7770glvhtmi8o/INVICTUS2.png

**Comment by c055** [comment]
let me know what do you think 

![iii_icon_final](https://f.cloud.github.com/assets/6280810/1844817/a3532c28-7555-11e3-93df-20eb0d4652a2.png)
